# This secret can also be created from the command line using environment variables
#
# export DATABASE_URI='postgresql://<place-url-to-database-here>'
# export POSTGRES_PASSWORD='<place-password-here>'
#
# kubectl create secret generic postgres-creds \
#     --from-literal=password=$POSTGRES_PASSWORD
#     --from-literal=database_uri=$DATABASE_URI
#
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: cGdzM2NyM3Q=
  database_uri: |
      cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cGdzM2NyM3RAcG9zdGdyZXM6NTQzMi9wZXRz
      dG9yZQ==
